[GLOBAL]
pants_version = "2.17.0"

backend_packages = ["pants.backend.python"]

[source]
root_patterns = ["edmmp/service_a", "edmmp/util"]

[python]
interpreter_constraints = ["==3.11.*"]
enable_resolves = true
default_resolve = "edmmp"

[python.resolves]
edmmp = "3rdparty/python/edmmp"

[python-infer]
use_rust_parser = true
